services:
  rabbitmq:
    image: "rabbitmq:3.13.6-management-alpine"
    container_name: 'rabbitmq-scs-training'
    hostname: 'rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
volumes:
  rabbitmq_data:

